spring:
  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # DDL 기능 사용 여부(create/update/create-drop/validate/none) / 운영DB에서는 사용 금지
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true # 콘솔에 SQL 출력 여부
        format_sql: true # SQL 가독성 높여주는 formatting 여부

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
