# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
#    username: nahyeon
#    password: lsmi81

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_TYPE}
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true

  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
    region: ${S3_REGION}

  sentry:
    dsn: ${SENTRY_DSN}
    traces-sample-rate: 1.0
    enable-tracing: true
    logging:
      minimum-event-level: info
      minimum-breadcrumb-level: info