spring:
  datasource:
    url: ${dburl}
    username: ${dbusername}
    password: ${dbpassword}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        default_batch_fetch_size: 10
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
springdoc:
  api-docs:
    enabled: false

    