spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # DDL 기능 사용 여부(create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true # 콘솔에 SQL 출력 여부
        format_sql: true # SQL 가독성 높여주는 formatting 여부

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
