spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_TYPE}
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secret: ${JWT_SECRET_KEY}

s3:
  key:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
  bucket-name:
    member-photo: ${S3_MEMBER_PHOTO_BUCKET_NAME}
    post-photo: ${S3_POST_PHOTO_BUCKET_NAME}
  region: ${S3_REGION}
  logo: ${S3_LOGO_IMG_URL}

sentry:
  dsn: ${SENTRY_DSN}
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

firebase:
  project-id: ${FCM_PROJECT_ID}
  private-key-id: ${FCM_PRIVATE_KEY_ID}
  private-key: ${FCM_PRIVATE_KEY}
  client-email: ${FCM_CLIENT_EMAIL}
  client-id: ${FCM_CLIENT_ID}
  client-url: ${FCM_CLIENT_URL}

logging:
  file:
    path: ${LOGGING_ROLLING_FILE_PATH}
    name: idorm-rolling.log
  level:
    org:
      springframework.web: info
      hibernate: info

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /index.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha