# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
#    username: nahyeon
#    password: lsmi81

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_TYPE}
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

#  logging:
#    level:
#      org:
#        hibernate:
#          type:
#            descriptor:
#              sql: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true

# S3
s3.accessKey: ${S3_ACCESS_KEY}
s3.secretKey: ${S3_SECRET_KEY}
s3.bucketName: ${S3_BUCKET_NAME}
s3.region: ${S3_REGION}