server:
  shutdown: graceful

spring:
  datasource:
    #    name: classpath:application.yml, /home/ec2-user/idorm-test/application-develop.yml
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_TYPE}
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: Asia/Seoul
    generate-ddl: false
    open-in-view: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
      enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwNTg5NDMxMiwiaWF0IjoxNzA1ODk0MzEyfQ.FhuQUTWCvIuIHJnpgTRk0_bn1Ku0R8rA6KEALrhuhRo
      expire-length:
        access: 3600000
        refresh: 1210000000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: ${DB_MIGRATION_SCRIPT_PATH}

# JPA log
logging:
  level:
    org.hibernate:
      SQL: WARN
      orm.jdbc.bind: WARN
    idorm.idormServer: WARN
  file:
    name: ${LOGGING_FILE_PATH}/idorm.log
  logback:
    rolling policy:
      clean-history-on-start: false
      file-name-pattern: ${LOGGING_FILE_PATH}/idorm--%d{yyyy-MM-dd}-%i.gz
      total-size-cap: 10MB

s3:
  key:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
  bucket-name:
    member-photo: ${S3_MEMBER_PHOTO_BUCKET_NAME}
    post-photo: ${S3_POST_PHOTO_BUCKET_NAME}
  region: ${S3_REGION}
  logo: ${S3_LOGO_IMG_URL}

sentry:
  dsn: ${SENTRY_DSN}
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: info

firebase:
  project-id: ${FCM_PROJECT_ID}
  private-key-id: ${FCM_PRIVATE_KEY_ID}
  private-key: ${FCM_PRIVATE_KEY}
  client-email: ${FCM_CLIENT_EMAIL}
  client-id: ${FCM_CLIENT_ID}
  client-url: ${FCM_CLIENT_URL}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus