spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      max-lifetime: 600000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000

    dbcp2:
      validation-query: select 1 from dual
      test-while-idle: true
      time-between-eviction-runs-millis: 600000

  jpa:
    hibernate:
      ddl-auto: none # DDL 기능 사용 여부(create/update/create-drop/validate/none)
    properties:
      hibernate:
        show_sql: true # 콘솔에 SQL 출력 여부
        format_sql: true # SQL 가독성 높여주는 formatting 여부
        default_batch_fetch_size: 10

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE


#springdoc:
#  api-docs:
#    enabled: true